### ISSUE TITLE
Unable to pack in ubuntu trusty

### ISSUE THREAD

**Issue by enboig** [jungleji/android_device_softwinner_cubieboard1#1]
7I have ubuntu trusty, compiled evereything using oracle java 7, but pack-cm returns:

!!Packing for android!!!
«chips/sun4i/configs/android/default/env_mmc.cfg» -> «out/env_mmc.cfg»
«chips/sun4i/configs/android/default/env_nand.cfg» -> «out/env_nand.cfg»
«chips/sun4i/configs/android/default/image.cfg» -> «out/image.cfg»
«chips/sun4i/configs/android/cubieboard/sys_config1.fex» -> «out/sys_config1.fex»
«chips/sun4i/configs/android/cubieboard/sys_config.fex» -> «out/sys_config.fex»
«../u-boot.bin» -> «bootfs/linux/u-boot.bin»
argc = 2
input name sys_config.fex
Script 1 source file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config.fex
Script 1 bin file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config.bin
parser 1 file ok
argc = 2
input name sys_config1.fex
Script 1 source file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config1.fex
Script 1 bin file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config1.bin
parser 1 file ok

update source file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config1.bin
boot0 file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/boot0.bin
boot1 file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/boot1.bin

update ok

update source file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config1.bin
boot0 file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/card_boot0.fex
boot1 file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/card_boot1.fex

update ok
mbr count = 4
mbr size  = 16777216
download map file = /home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/dlinfo.fex

partitation file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/sys_config.bin
mbr_name file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/mbr.fex
download_name file Path=/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/dlinfo.fex

update mbr: partcount = 9
update mbr file ok
mkdir: s’ha creat el directori «bootfs/vendor»
mkdir: s’ha creat el directori «bootfs/vendor/system»
mkdir: s’ha creat el directori «bootfs/vendor/system/media»
disk : c
CopyRootToFS(/home/user/android/cubieboard/cb-cm-10.1/tools/pack/out/bootfs)

c:\sprite

c:\linux

c:\os_show

c:\vendor

c:\vendor\system

c:\vendor\system\media
c:\magic.bin
find magic !! 
RealLen=0x6A6400
CPlugin Free lib 
CPlugin Free lib 
FileLength=6a6400 FileSizeHigh=0
FileLength=40000 FileSizeHigh=0
 CreateFile failed 2
 CreateFile failed 2
 CreateFile failed 2
 CreateFile failed 2
 CreateFile failed 2
/home/user/android/cubieboard/cb-cm-10.1/tools/pack/pctools/linux/eDragonEx//home/user/android/cubieboard/cb-cm-10.1/tools/pack/outFile boot.fex Not ExistBuildImg 360
Dragon execute image.cfg Failed ! 360
CPlugin Free lib 
CPlugin Free lib

**Comment by jungleji** [comment]
The error message said it cannot find boot.fex file. I think cache.fex, data.fex, system.fex, data.fex, recovery.fex missing too.
This boot.fex is a link to boot.img that generated in android output directory.
You can use `ls -l tools/pack/out` to check it.

**Comment by enboig** [comment]
I created the files in ~/cb-cm-10.1/tools/pack/out
but they sould go to ~/cb-cm-10.1/out/target/product/cubieboard1

thanks
