### ISSUE TITLE
Invalid image 

### ISSUE THREAD

**Issue by enboig** [jungleji/android_device_softwinner_cubieboard1#2]
After packing the image (around 2gb) when I try to flash it livesuit and Phoenix complain about invalid image, I also tried dd it to a sdcard. What am I missing? The file is sun4i_android_cibieboard.img

**Comment by jungleji** [comment]
The img file generated by pack-cm.sh is a nand image, not for sdcard.

You need check the pack-cm.sh output message, to find if there are some error messages. If success, it will print out "Dragon execute image.cfg SUCCESS !". 

The size of sun4i_android_cibieboard.img I generated is about 1.4G, if you adjust the partition size, you need make sure the total size is not over cubieboard 4G nand size. 

And the flash tools I used is PhoenixSuit v1.08.

**Comment by enboig** [comment]
I have been able to flash the image. Some times it flashes ok and some fail. I reduced data.img and cache.img drastically to minimize fails.

Thanks.
